global:
  logging:
    level: "DEBUG"
    formatter: "default"
  plugin:
    plugin_path: "./plugins"
    plugin_repo_path: "./repos"
    default_repo: "RoLLeRHub"
  pei:
    version: "v1"
plugins:
  ssh_plugin:
    timeout_ms: 10000